version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: inmusic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: InfraMusicStore
    volumes:
      - ./db/init_struct.sql:/docker-entrypoint-initdb.d/01_init_struct.sql
      - ./db/init_data.sql:/docker-entrypoint-initdb.d/02_init_data.sql
    ports:
      - "3307:3306"

  api:
    build: api
    container_name: inframusicstore-api
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - ./api/.env

  adminer:
    image: adminer
    container_name: inframusicstore-adminer-1
    restart: always
    ports:
      - "8080:8080"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: inframusicstore-swagger
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.yml
    volumes:
      - ./docs/swagger.yml:/docs/swagger.yml
